site_name: Documentação do Projeto
site_description: Base inicial da documentação tecnica e organizacional
site_url: "https://enzoemir.github.io/IDB_JOVEM_DOC/"

repo_url: "https://github.com/EnzoEmir/IDB_JOVEM_DOC"
repo_name: Repositorio

theme:
  name: material
  language: pt-BR
  logo: imagens/logo.png
  favicon: imagens/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Alternar para tema claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Alternar para tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Usar preferência do sistema
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy

extra_css:
  - stylesheets/custom.css

nav:
  - Inicio: index.md
  - Projeto:
      - História: projeto/historia_usuario_novo.md
      - Backlog: projeto/backlog_novo.md
      - Backlog de Melhorias: projeto/backlog_melhorias.md
      - Sprints: projeto/sprints.md
      - Matriz de Autorização: projeto/matriz-autorizacao.md
      - Canvas MVP: projeto/canvas_mvp.md
      - Protótipo de alta fidelidade: projeto/prototipo_alta.md
      - Modelo Físico: projeto/modelo_fisico.md
      - Vídeo entrega Final: projeto/entrega_final.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
